### ISSUE TITLE
Fill in app icon's white space inside the circle

### ISSUE THREAD

**Issue by simonyangme** [jontelang/WakaLet#15]
![wakalet-icon](https://cloud.githubusercontent.com/assets/48696/7802756/9eec5ac6-02f1-11e5-9ca2-d505915a6e4f.png)

**Comment by Sidetalker** [comment]
Submitted a pull request!

**Comment by jontelang** [comment]
Cool, thanks both of you, I will merge it and also probably do a new release version after the fact.

**Comment by Sidetalker** [comment]
You bet - go WakaTime!

**Comment by jontelang** [comment]
@Sidetalker I just pulled it down and had a look. It seems like you filled in one of the icons, but only the one for "set API key". I had forgot to remove that one, the actual app icons are actually in images.xcassets. I booted up photoshop to include the rest as well.

**Comment by Sidetalker** [comment]
Oops, I definitely didn’t look at the source - sorry about that and thanks for taking care of it.

**Comment by jontelang** [comment]
No worries, it brought light to some issues with the project :+1:
