### ISSUE TITLE
Projects appear clickable when refresh-rebuild while having the menu open

### ISSUE THREAD

**Issue by jontelang** [jontelang/WakaLet#2]
They all become white, as opposed to gray.

**Comment by 2Grey** [comment]
@jontelang , set MenuItem enabled property to NO, like here:
https://github.com/2Grey/WakaLet/commit/624847e5cde140189446099af9eae2eb633b6117

**Comment by jontelang** [comment]
@2Grey Ohh, that makes sense! Will you do a PR?

**Comment by 2Grey** [comment]
@jontelang your turn.
