### ISSUE TITLE
Very long timeline and can't update

### ISSUE THREAD

**Issue by Tusko** [jontelang/WakaLet#20]
The latest date is 11th September 2016
https://cl.ly/i35v

**Comment by jontelang** [comment]
Sorry for the late reply.

Are you running the code or have you made some changes? The code itself should only look at 7 days behind as it is hard coded. https://github.com/jontelang/WakaLet/blob/master/WakaLet/AppDelegate.m#L42-L48

Does this happen all the time, or was it a one-off thing? If you can take a look at the url generated via Xcode or something that would help.

You can force a refresh with CMD+R when the menu is open.
