### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by rposborne** [jontelang/WakaLet#4]
Cause, awesome.

**Comment by Greenek** [comment]
+1

**Comment by phoebejaffe** [comment]
+2!

**Comment by larrybolt** [comment]
:+1: I'd love to see this too, and perhaps as well adding to [homebrew-cask](http://github.com/caskroom/homebrew-cask)

**Comment by alfonsomga** [comment]
+1 
This is awesome.

**Comment by jontelang** [comment]
I'll get on this. By release you guys mean a .app to download, right? (I'm fairly new to "proper"  OSX application coding).

**Comment by larrybolt** [comment]
@jontelang a compiled version (.app) as a release, even though a lot developers have xcode installed (for command line tools for instance), using xcode without experience is a pain, just been searching for over 10 minutes where on earth xcode placed the build.

For the others that want to start trying it out and don't feel like opening xcode themselves: http://lry.be/ipwS

**Comment by 2Grey** [comment]
@jontelang: 
1) Build project in Xcode;
2) In Xcode open Products folder;
3) Right click by wakalet.app;
4) Show in Finder.

**Comment by jontelang** [comment]
Yep, I've gone through the "where the heck is the .app" file before actually. I was more wondering if that's all I need to do. I know that when I used to be on windows there was all sorts of things needed to be done to ensure that it ran "everywhere".

Anyway, release version 0.1 can be found at https://github.com/jontelang/WakaLet/releases/

:)

**Comment by jontelang** [comment]
@larrybolt Feel free to add that homebrew thing as a separate issue, and I'll get to looking into that when I've got some time over.

**Comment by rposborne** [comment]
:heart: :heart_eyes: :+1: :clap:
